# SPDX-License-Identifier: GPL-3.0-only

[package]
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
repository.workspace = true
version.workspace = true
name = "spalst_derives"
license-file = "../LICENSE.md"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lints]
workspace = true

