[package]
edition.workspace = true
repository.workspace = true
name = "spalstatui"
version = "0.30.0"
license-file = "../LICENSE.md"
description = "Ratatui fork tailored for Spalst."
keywords = ["tui", "terminal"]
categories = ["command-line-interface"]
readme = "./README.md"

[dependencies]
color-eyre.workspace = true
crossterm.workspace = true
ratatui.workspace = true

[lints]
workspace = true
